<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OptimizationPreference>Speed</OptimizationPreference>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath Condition="'$(Configuration)'=='Debug'">bin\Debug\net8.0\</OutputPath>
    <OutputPath Condition="'$(Configuration)'=='Release'">bin\Release\net8.0\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.11" />
  </ItemGroup>
</Project>
