<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>subspace</AssemblyName>
    <RootNamespace>Subspace</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DiscUtils.Vhdx" Version="0.16.13" />
    <PackageReference Include="DiscUtils.Vhd" Version="0.16.13" />
    <PackageReference Include="DiscUtils.FileSystems" Version="0.16.13" />
    <PackageReference Include="DiscUtils.Ntfs" Version="0.16.13" />
    <PackageReference Include="DiscUtils.Fat" Version="0.16.13" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="LibVLCSharp" Version="3.8.5" />
    <PackageReference Include="LibVLCSharp.WinForms" Version="3.8.5" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.20" />
  </ItemGroup>
</Project>
